/**
 * AUTOGENERATED via openwrt-docs4ai stage 05e
 * Target: Language Server Protocol (LSP) IDE autocomplete for LuCI JavaScript framework
 * Source: JS source files parsed from repo-luci (Approach 2 — see script docstring)
 */

// ============================================================
// LuCI global namespace
// ============================================================

declare namespace LuCI {

  // ----------------------------------------------------------
  // LuCI.uci — UCI configuration access
  // ----------------------------------------------------------

  namespace uci {
    /** Internal representation of a UCI section including metadata fields. */
    interface SectionObject {
      ".anonymous": boolean;
      ".index":     number;
      ".name":      string;
      ".type":      string;
      [option: string]: string | string[] | boolean | number;
    }

    function load(packages: string | string[]): Promise<string[]>;
    function unload(packages: string | string[]): void;
    function add(conf: string, type: string, name?: string): string;
    function remove(conf: string, sid: string): void;
    function sections(conf: string, type?: string, cb?: (section: SectionObject, sid: string) => void): SectionObject[];
    function get(conf: string, sid: string, opt?: string): string | string[] | SectionObject | null;
    function set(conf: string, sid: string, opt: string, val: string | string[] | null): void;
    function unset(conf: string, sid: string, opt: string): null;
    function save(): Promise<void>;
    function apply(timeout?: number): Promise<void>;
  }

  // ----------------------------------------------------------
  // LuCI.rpc — ubus JSON-RPC abstraction
  // ----------------------------------------------------------

  namespace rpc {
    /** Options object passed to rpc.declare(). */
    interface DeclareOptions {
      object:   string;
      method:   string;
      params?:  string[];
      expect?:  Record<string, unknown>;
      filter?:  (data: unknown, args: unknown[], ...extra: unknown[]) => unknown;
      reject?:  boolean;
      nobatch?: boolean;
    }

    /**
     * Describes a remote RPC call procedure and returns an invocation function.
     * @param options RPC call declaration options.
     * @returns A function that, when called, dispatches the ubus RPC request.
     */
    function declare(options: DeclareOptions): (...args: unknown[]) => Promise<unknown>;

    /**
     * Registers an interceptor function for all RPC call replies.
     * @param interceptorFn Function to call for every RPC reply.
     * @returns The registered interceptor function.
     */
    function addInterceptor(interceptorFn: (msg: unknown, req: unknown) => Promise<void>): (msg: unknown, req: unknown) => Promise<void>;

    /**
     * Removes a previously registered interceptor function.
     * @param interceptorFn The interceptor function to remove.
     */
    function removeInterceptor(interceptorFn: (msg: unknown, req: unknown) => Promise<void>): void;

    /**
     * Returns the current RPC session ID.
     * @returns 32-byte session ID string.
     */
    function getSessionID(): string;
  }

  // ----------------------------------------------------------
  // LuCI.form — declarative UCI form binding API
  // ----------------------------------------------------------

  namespace form {

    // Abstract base element
    class AbstractElement {
      render(sectionId?: string, ...args: unknown[]): Promise<Node>;
      load(sectionId?: string, ...args: unknown[]): Promise<unknown>;
      parse(sectionId?: string, ...args: unknown[]): Promise<void>;
    }

    // Abstract section
    class AbstractSection extends AbstractElement {
      anonymous: boolean;
      dynamic:   boolean;
      optional:  boolean;
      addOption<T extends AbstractValue>(
        optionClass: new (...args: unknown[]) => T,
        ...args: unknown[]
      ): T;
      getOption(name: string, sectionId?: string): AbstractValue | null;
      getUIElement(sectionId: string, option?: string): unknown;
      formvalue(sectionId: string, option?: string): string | string[] | null;
      cfgvalue(sectionId: string, option?: string): string | string[] | null;
    }

    /**
     * Represents a UCI configuration form backed by a real UCI config.
     * @param config  The UCI configuration name (e.g. 'network', 'firewall').
     * @param title   Optional title displayed above the form.
     * @param description Optional description text.
     */
    class Map extends AbstractElement {
      constructor(config: string, title?: string, description?: string);
      section<T extends AbstractSection>(
        sectionClass: new (...args: unknown[]) => T,
        ...args: unknown[]
      ): T;
      render(): Promise<Node>;
      save(cb?: () => void, silent?: boolean): Promise<void>;
      reset(): Promise<void>;
      lookupOption(name: string, sectionId?: string, configName?: string): [AbstractValue, string] | null;
    }

    /**
     * Like Map but backed by a plain in-memory JS object instead of UCI.
     */
    class JSONMap extends Map {
      constructor(
        data: Record<string, Record<string, unknown> | Array<Record<string, unknown>>>,
        title?: string,
        description?: string
      );
    }

    /**
     * A section type that groups all UCI sections of a given type.
     * @param map      The parent Map instance.
     * @param uciTypeName  The UCI section type to enumerate (e.g. 'interface').
     * @param className    Human-readable section title.
     * @param title        Optional table/section heading.
     * @param description  Optional section description.
     */
    class TypedSection extends AbstractSection {
      anonymous:    boolean;
      addremove:    boolean;
      extedit:      string | null;
      sortable:     boolean;
      filter(sectionId: string, sectionData: Record<string, unknown>): boolean;
    }

    /**
     * A section type rendered as an HTML table.
     */
    class TableSection extends TypedSection {
      rowActions:         boolean;
      addDialogue:        string | null;
      modaltitle:         string | null;
    }

    /**
     * A section type bound to a specific, named UCI section.
     * @param map      The parent Map instance.
     * @param uciName  The UCI section name.
     * @param className  Human-readable class name.
     * @param title    Optional section title.
     * @param description Optional section description.
     */
    class NamedSection extends AbstractSection {
      addremove: boolean;
    }

    // Abstract value/option base
    class AbstractValue extends AbstractElement {
      default:      string | null;
      optional:     boolean;
      rmempty:      boolean;
      depends(optionOrDict: string | Record<string, string | boolean>, value?: string | boolean): AbstractValue;
      retain(keep: boolean): AbstractValue;
      validate(sectionId: string, value: string): true | string;
      cfgvalue(sectionId: string): string | string[] | null;
      formvalue(sectionId: string): string | string[] | null;
      write(sectionId: string, formvalue: string | string[]): void | Promise<void>;
    }

    /**
     * A plain text input field mapped to a UCI option.
     * @param map       The parent Map or section.
     * @param section   The UCI section type.
     * @param option    The UCI option name.
     * @param title     Human-readable label.
     * @param description Optional tooltip/description.
     */
    class Value extends AbstractValue {
      placeholder:  string | null;
      password:     boolean;
    }

    /** A dynamic list (UCI list option). */
    class DynamicList extends AbstractValue {}

    /** A drop-down select widget. */
    class ListValue extends AbstractValue {
      value(key: string, val?: string): ListValue;
      keylist(sectionId: string): string[];
      vallist(sectionId: string): string[];
    }

    /** A checkbox (boolean UCI option). */
    class Flag extends AbstractValue {
      enabled:  string;
      disabled: string;
    }

    /** A multi-select list. */
    class MultiValue extends ListValue {
      display_size:  number | null;
      optional_size: number | null;
      size:          number | null;
    }

    /** A multi-line text area. */
    class TextValue extends AbstractValue {
      rows:     number | null;
      cols:     number | null;
      wrap:     boolean;
      monospace: boolean;
    }

    /** A static label (no input). */
    class DummyValue extends AbstractValue {}

    /** A push-button element with an action callback. */
    class Button extends AbstractValue {
      inputtitle: string | null;
      inputstyle: string | null;
    }

    /** A hidden input field. */
    class HiddenValue extends AbstractValue {}

  }

  // ----------------------------------------------------------
  // LuCI.view — view lifecycle base class
  // ----------------------------------------------------------

  namespace view {
    /**
     * Base class for LuCI views. Override load() and render() at minimum.
     */
    class view {
      /**
       * Called before render(); may return a Promise.
       * The resolved value is passed as the first argument to render().
       */
      load(): unknown | Promise<unknown>;

      /**
       * Called after load() with the resolved load data.
       * Must return a DOM Node (or a Promise thereof) to display.
       */
      render(data?: unknown): Node | Promise<Node>;

      /**
       * Called when the user clicks the Save button.
       * Default implementation calls map.save() on all child form maps.
       */
      handleSave(ev: Event): Promise<void>;

      /**
       * Called when the user clicks Save & Apply.
       * Default: save then call uci.apply().
       */
      handleSaveApply(ev: Event, mode: 'apply' | 'revert'): Promise<void>;

      /**
       * Called when the user clicks Reset.
       */
      handleReset(ev: Event): Promise<void>;

      /**
       * Appends the standard Save/Save &amp; Apply/Reset footer buttons.
       * @returns DOM Node with footer buttons.
       */
      addFooter(): Node;
    }
  }

  // ----------------------------------------------------------
  // LuCI.dom — DOM manipulation utilities
  // ----------------------------------------------------------

  namespace dom {
    /** Returns true if the value is a DOM Node. */
    function elem(e: unknown): e is Node;

    /**
     * Parses an HTML fragment and returns the first child node.
     * @param s HTML fragment string.
     */
    function parse(s: string): Node | null;

    /**
     * Tests whether a node matches a CSS selector.
     * @param node     Node to test.
     * @param selector CSS selector string.
     */
    function matches(node: unknown, selector?: string): boolean;

    /**
     * Finds the closest ancestor matching the given selector.
     * @param node     Starting node.
     * @param selector CSS selector.
     * @param until    Stop searching at this node.
     */
    function parent(node: Node, selector: string, until?: Node): Node | null;

    /**
     * Appends children to a node.  Children may be Nodes, strings, or Arrays.
     * @param node     Target node.
     * @param children Content to append.
     */
    function append(node: Node, children: unknown): Node;

    /**
     * Replaces all children of a node.
     * @param node     Target node.
     * @param children New content.
     */
    function content(node: Node, children: unknown): Node;

    /**
     * Gets or sets HTML attributes on an element.
     * @param node    Target element.
     * @param attr    Attribute name or object of attribute→value pairs.
     * @param val     Attribute value (when attr is a string).
     */
    function attr(node: Element, attr: string | Record<string, string | null>, val?: string | null): null;

    /**
     * Gets or sets arbitrary data associated with a node.
     * @param node  Target node.
     * @param key   Data key.
     * @param val   Data value to set (omit to get).
     */
    function data(node: Node, key: string, val?: unknown): unknown;

    /**
     * Binds a class instance to all matching methods in the node.
     * @param node      Target node.
     * @param inst      Class instance to bind.
     */
    function bindClassInstance(node: Node, inst: object): Node;
  }

  // ----------------------------------------------------------
  // LuCI.request — HTTP request API
  // ----------------------------------------------------------

  namespace request {
    interface RequestOptions {
      method?:      string;
      headers?:     Record<string, string>;
      content?:     string | FormData | Record<string, unknown>;
      timeout?:     number;
      credentials?: boolean;
      responseType?: string;
    }

    interface Response {
      ok:         boolean;
      status:     number;
      statusText: string;
      headers:    Record<string, string>;
      json():     unknown;
      text():     string;
      blob():     Blob;
    }

    /** Issues an HTTP GET request. */
    function get(url: string, options?: RequestOptions): Promise<Response>;

    /** Issues an HTTP POST request. */
    function post(url: string, data?: unknown, options?: RequestOptions): Promise<Response>;

    /** Cancels all pending HTTP requests. */
    function cancel(): void;
  }

  // ----------------------------------------------------------
  // LuCI.network — network model API (stub)
  // ----------------------------------------------------------
  //
  // Note: The full network.js API is extensive (>3000 lines).
  // Only the top-level class declaration is included here to
  // enable basic usage without auto-discovery of the full surface.
  // ----------------------------------------------------------

  namespace network {
    interface Protocol {
      readonly ifname:   string;
      readonly type:     string;
      getIfname():       string;
      getProtocol():     string;
      isFloating():      boolean;
      isVirtual():       boolean;
    }

    interface Device {
      readonly name: string;
      getName():     string;
      getType():     string;
      getMAC():      string | null;
      getMTU():      number;
    }

    /**
     * Load and return all network interfaces.
     * @returns Promise resolving to array of Protocol objects.
     */
    function getNetworks(): Promise<Protocol[]>;

    /**
     * Load and return all network devices.
     */
    function getDevices(): Promise<Device[]>;

    /**
     * Look up a specific network interface by name.
     */
    function getNetwork(name: string): Promise<Protocol | null>;
  }

}

// ---------------------------------------------------------------------------
// Global helpers available in every LuCI view context
// ---------------------------------------------------------------------------

/** The global LuCI instance. */
declare const L: typeof LuCI & {
  env: {
    sessionid:  string;
    token:      string;
    rpctimeout: number;
    ubuspath:   string;
    [key: string]: unknown;
  };
  /** Constructs a URL relative to the LuCI root. */
  url(...parts: string[]): string;
  /** Returns true if the argument is a plain object. */
  isObject(val: unknown): val is Record<string, unknown>;
  /** Resolves a require specifier and returns the module. */
  require(module: string): Promise<unknown>;
  /** Raises an exception with a given type and formatted message. */
  raise(errType: string, fmt: string, ...args: unknown[]): never;
};

/**
 * Creates a DOM element.
 * Equivalent of document.createElement but with attribute and child support.
 */
declare function E(
  tag: string,
  attrs?: Record<string, string | boolean | null | undefined> | null,
  children?: Node | string | Array<Node | string | null | undefined> | null
): HTMLElement;

/**
 * Translates a string using the loaded i18n catalogue.
 * Short alias for LuCI.prototype.i18n.
 */
declare function _(key: string, ...args: unknown[]): string;
