/**
 * AUTOGENERATED VIA openwrt-docs4ai
 * Target: Language Server Protocol (LSP) IDE Autocomplete
 */

declare module "buffer" {
    export function end(______buffer____module_struct_buffer: any): any;
    export function get(format: any): any;
    export function length(_length______number_______buffer____module_struct_buffer: any): any;
    export function pos(_position______number_______buffer____module_struct_buffer: any): any;
    export function pull(): any;
    export function put(format: any, ___values______buffer____module_struct_buffer: any): any;
    export function set(value?: any, start?: any, _end_______buffer____module_struct_buffer: any): any;
    export function slice(start?: any, end?: any): any;
    export function start(______buffer____module_struct_buffer: any): any;
}

declare module "cursor" {
    export function ChangeRecord(): any;
    export function ParserFlags(): any;
    export function SectionCallback(): any;
    export function SectionObject(): any;
    export function add(config: any, type: any): any;
    export function changes(config?: any): any;
    export function commit(config?: any): any;
    export function configs(): any;
    export function delete(config: any, section: any, option?: any): any;
    export function error(): any;
    export function foreach(config: any, type: any, callback: any): any;
    export function get(): any;
    export function list(): any;
    export function load(config: any): any;
    export function rename(config: any, section: any, option_or_name: any, name?: any): any;
    export function reorder(config: any, section: any, index: any): any;
    export function revert(config?: any): any;
    export function save(config?: any): any;
    export function set(config: any, section: any, option_or_type: any, value?: any): any;
    export function unload(config: any): any;
}

declare module "debug" {
    export function LocalInfo(): any;
    export function SourcePosition(): any;
    export function StackTraceEntry(): any;
    export function UpvalInfo(): any;
    export function UpvalRef(): any;
    export function ValueInformation(): any;
    export function getinfo(value______ValueInformation____module_debug_ValueInformation: any): any;
    export function getlocal(level?: any, variable______LocalInfo____module_debug_LocalInfo: any): any;
    export function getupval(target: any, variable______UpvalInfo____module_debug_UpvalInfo: any): any;
    export function memdump(file: any): any;
    export function setlocal(level?: any, variable: any, _value_______LocalInfo____module_debug_LocalInfo: any): any;
    export function setupval(target: any, variable: any, value______UpvalInfo____module_debug_UpvalInfo: any): any;
    export function sourcepos(______SourcePosition____module_debug_SourcePosition: any): any;
    export function traceback(_level_______Array__StackTraceEntry_____module_debug_StackTraceEntry: any): any;
}

declare module "deflate" {
    export function error(): any;
    export function read(): any;
    export function write(src: any, flush?: any): any;
}

declare module "digest" {
    export function md2(): any;
    export function md4(): any;
    export function md5(): any;
    export function sha1(): any;
    export function sha256(): any;
    export function sha384(): any;
    export function sha512(): any;
}

declare module "dir" {
    export function close(): any;
    export function error(): any;
    export function fileno(): any;
    export function read(): any;
    export function seek(offset: any): any;
    export function tell(): any;
}

declare module "file" {
    export function close(): any;
    export function error(): any;
    export function fileno(): any;
    export function flush(): any;
    export function ioctl(direction: any, type: any, num: any, value?: any): any;
    export function isatty(): any;
    export function lock(op?: any): any;
    export function read(length: any): any;
    export function seek(offset?: any, position?: any): any;
    export function tell(): any;
    export function truncate(offset?: any): any;
    export function write(data: any): any;
}

declare module "fs" {
    export function FileStatResult(): any;
    export function ST(): any;
    export function StatVFSResult(): any;
    export function access(path: any, mode?: any): any;
    export function basename(path: any): any;
    export function chdir(path: any): any;
    export function chmod(path: any, mode: any): any;
    export function chown(path: any, uid?: any, gid?: any): any;
    export function dir(): any;
    export function dirname(path: any): any;
    export function dup2(oldfd: any, newfd: any): any;
    export function error(): any;
    export function fdopen(fd: any, mode?: any): any;
    export function file(): any;
    export function getcwd(): any;
    export function glob(___pattern: any): any;
    export function lsdir(path: any): any;
    export function lstat(path______FileStatResult____module_fs_FileStatResult: any): any;
    export function mkdir(path: any): any;
    export function mkdtemp(template?: any): any;
    export function mkstemp(_template_______file____module_fs_file: any): any;
    export function open(path: any, mode?: any, _perm_______file____module_fs_file: any): any;
    export function opendir(path______dir____module_fs_dir: any): any;
    export function pipe(______Array__file_____module_fs_file: any): any;
    export function popen(command: any, _mode_______proc____module_fs_proc: any): any;
    export function proc(): any;
    export function readfile(path: any, limit?: any): any;
    export function readlink(path: any): any;
    export function realpath(path: any): any;
    export function rename(oldPath: any, newPath: any): any;
    export function rmdir(path: any): any;
    export function stat(path______FileStatResult____module_fs_FileStatResult: any): any;
    export function statvfs(path______StatVFSResult____module_fs_StatVFSResult: any): any;
    export function symlink(target: any, path: any): any;
    export function unlink(path: any): any;
    export function writefile(path: any, data: any, limit?: any): any;
}

declare module "handle" {
    export function close(): any;
    export function delete(): any;
    export function dup(______handle____module_io_handle: any): any;
    export function dup2(newfd: any): any;
    export function error(): any;
    export function fcntl(cmd: any, _arg______number_______handle____module_io_handle: any): any;
    export function fileno(): any;
    export function grantpt(): any;
    export function handle(): any;
    export function ioctl(direction: any, type: any, num: any, value?: any): any;
    export function isatty(): any;
    export function ptsname(): any;
    export function read(length: any): any;
    export function seek(offset?: any, whence?: any): any;
    export function tcgetattr(): any;
    export function tcsetattr(attrs: any, when?: any): any;
    export function tell(): any;
    export function unlockpt(): any;
    export function write(data: any): any;
}

declare module "inflate" {
    export function error(): any;
    export function read(): any;
    export function write(src: any, flush?: any): any;
}

declare module "instance" {
    export function pack(___values: any): any;
    export function unpack(input: any, offset?: any): any;
}

declare module "interval" {
    export function cancel(): any;
    export function expirations(): any;
    export function remaining(): any;
    export function set(interval?: any): any;
}

declare module "io" {
    export function error(): any;
    export function from(value______handle____module_io_handle: any): any;
    export function handle(): any;
    export function new(fd______handle____module_io_handle: any): any;
    export function open(path: any, flags?: any, _mode_______handle____module_io_handle: any): any;
    export function pipe(______Array__handle_____module_io_handle: any): any;
}

declare module "listener" {
    export function close(): any;
    export function set(): any;
}

declare module "log" {
    export function ERR(format: any, ___args?: any): any;
    export function INFO(format: any, ___args?: any): any;
    export function LogFacility(): any;
    export function LogOption(): any;
    export function LogPriority(): any;
    export function NOTE(format: any, ___args?: any): any;
    export function UlogChannel(): any;
    export function WARN(format: any, ___args?: any): any;
    export function closelog(): any;
    export function openlog(ident?: any, options?: any, facility?: any): any;
    export function syslog(priority: any, format: any, ___args?: any): any;
    export function ulog(): any;
}

declare module "math" {
    export function abs(number: any): any;
    export function atan2(y: any, x: any): any;
    export function cos(x: any): any;
    export function exp(x: any): any;
    export function isnan(x: any): any;
    export function log(x: any): any;
    export function pow(x: any, y: any): any;
    export function rand(a?: any, b?: any): any;
    export function sin(x: any): any;
    export function sqrt(x: any): any;
    export function srand(seed: any): any;
}

declare module "nl80211" {
    export function listener(): any;
}

declare module "pipe" {
    export function receive(): any;
    export function receiving(): any;
    export function send(msg: any): any;
    export function sending(): any;
}

declare module "proc" {
    export function close(): any;
    export function error(): any;
    export function fileno(): any;
    export function flush(): any;
    export function read(length: any): any;
    export function write(data: any): any;
}

declare module "process" {
    export function delete(): any;
    export function pid(): any;
}

declare module "resolv" {
    export function error(): any;
    export function query(names: any, options?: any): any;
}

declare module "rtnl" {
    export function error(): any;
    export function listener(): any;
    export function request(cmd: any, flags: any, payload: any): any;
}

declare module "signal" {
    export function delete(): any;
    export function signo(): any;
}

declare module "socket" {
    export function AddressInfo(): any;
    export function ControlMessage(): any;
    export function PeerCredentials(): any;
    export function PollSpec(): any;
    export function ReceivedMessage(): any;
    export function SocketAddress(): any;
    export function accept(address?: any, _flags_______socket____module_socket_socket: any): any;
    export function addrinfo(hostname: any, service?: any, _hints_______Array__AddressInfo_____module_socket_AddressInfo: any): any;
    export function bind(address: any): any;
    export function close(): any;
    export function connect(address: any, port: any): any;
    export function create(domain?: any, type?: any, _protocol_______socket____module_socket_socket: any): any;
    export function error(numeric?: any): any;
    export function fileno(): any;
    export function getopt(level: any, option: any): any;
    export function listen(backlog?: any): any;
    export function nameinfo(address: any, flags?: any): any;
    export function open(_fd_______socket____module_socket_socket: any): any;
    export function pair(type?: any): any;
    export function peercred(______PeerCredentials____module_socket_socket_PeerCredentials: any): any;
    export function peername(______SocketAddress____module_socket_socket_SocketAddress: any): any;
    export function poll(timeout: any, ___sockets______Array__PollSpec_____module_socket_PollSpec: any): any;
    export function recv(length?: any, flags?: any, address?: any): any;
    export function recvmsg(sizes?: any, ancillarySize?: any, _flags_______ReceivedMessage____module_socket_socket_ReceivedMessage: any): any;
    export function send(data: any, flags?: any, address?: any): any;
    export function sendmsg(data?: any, ancillaryData?: any, address?: any, flags?: any): any;
    export function setopt(level: any, option: any, value: any): any;
    export function shutdown(how: any): any;
    export function sockaddr(address______SocketAddress____module_socket_socket_SocketAddress: any): any;
    export function socket(): any;
    export function sockname(______SocketAddress____module_socket_socket_SocketAddress: any): any;
    export function strerror(code: any): any;
}

declare module "struct" {
    export function buffer(): any;
    export function instance(): any;
    export function new(format______instance____module_struct_instance: any): any;
    export function pack(format: any, ___values: any): any;
    export function unpack(format: any, input: any, offset?: any): any;
}

declare module "task" {
    export function finished(): any;
    export function kill(): any;
    export function pid(): any;
}

declare module "timer" {
    export function cancel(): any;
    export function remaining(): any;
    export function set(timeout?: any): any;
}

declare module "uci" {
    export function cursor(): any;
    export function error(): any;
}

declare module "uloop" {
    export function cancelling(): any;
    export function done(): any;
    export function end(): any;
    export function error(): any;
    export function handle(): any;
    export function init(): any;
    export function interval(): any;
    export function pipe(): any;
    export function process(): any;
    export function run(timeout?: any): any;
    export function running(): any;
    export function signal(): any;
    export function task(): any;
    export function timer(): any;
}

declare module "zlib" {
    export function deflate(): any;
    export function deflater(gzip?: any, _level_______deflate____module_zlib_deflate: any): any;
    export function inflate(): any;
    export function inflater(______inflate____module_zlib_inflate: any): any;
}
